name = "vleam"
version = "1.0.0"
licences = ["Apache-2.0"]
description = "Vue composition API bindings for Gleam"

gleam = "~> 1.0"
target = "javascript"

repository = { type = "github", user = "vleam", repo = "vleam" }

[javascript]
typescript_declarations = true

[dependencies]
gleam_stdlib = ">= 0.41.0 and < 1.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
